site_name: Jubladb mit Nextcloud verbinden
site_url: https://niclasheinz.github.io/jubladb-nextcloud
repo_name: niclasheinz/jubladb-nextcloud 
repo_url: https://github.com/niclasheinz/jubladb-nextcloud
site_author: Niclas Heinz
edit_uri: edit/main/docs/

theme:
  name: material
  language: de
  features:
    - content.action.edit
    - content.action.view
  icon:
    edit: material/pencil
    view: material/eye
  theme:
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

# Plugins Configuration
plugins:
  - search
  - git-revision-date-localized:
      enabled: !ENV [CI, true]
      enable_creation_date: true
      fallback_to_build_date: true
  - git-committers:
      repository: niclasheinz/jubladb-nextcloud
      branch: main
      enabled: !ENV [CI, true]
      token: !ENV [GH_TOKEN]
  
# Markdown Extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.mark
  - attr_list
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
        # make exceptions to highlighting of code:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  