name: ci

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Configure Git Credentials
        run: |
          git config user.name "Niclas Heinz"
          git config user.email "nheinz@hpost.net"

      - name: Set GitHub Token
        run: echo "GH_TOKEN=${{ secrets.GH_TOKEN }}" >> $GITHUB_ENV  # Securely set token

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Cache Dependencies
        run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}-${{ hashFiles('requirements.txt') }}
          path: .cache
          restore-keys: |
            mkdocs-

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Deploy Documentation
        run: mkdocs gh-deploy --force
